[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.5",
    "django-ninja>=1.4",
    "gunicorn>=23.0.0",
    "openpyxl>=3.1.5",
    "pillow>=11.0",
    "pyjwt>=2.10",
    "pymysql>=1.2.0",
    "python-dotenv>=1.0",
    "qrcode[pil]>=8.0",
    "reportlab>=4.5.1",
    "whitenoise>=6.12.0",
]
