# Generated by Django 6.0.5 on 2026-06-05 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0002_activite_ville'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('excel', 'Liste Excel'), ('pdf_liste', 'Liste de présence (PDF)'), ('zip', 'Fiches CNI (ZIP)'), ('qrcode', 'Affiche QR Code (PDF)'), ('fiche_cni', 'Fiche CNI individuelle (PDF)')], max_length=20, verbose_name="type d'export")),
                ('nb_entrees', models.PositiveIntegerField(default=0, verbose_name="nombre d'entrées")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='activites.activite', verbose_name='activité')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_declenches', to=settings.AUTH_USER_MODEL, verbose_name='déclenché par')),
            ],
            options={
                'verbose_name': 'export',
                'verbose_name_plural': 'exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
