/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Vérification simple de disponibilité de l'API.
         */
        get: operations["config_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Connexion organisateur : retourne un couple de tokens JWT.
         */
        post: operations["apps_accounts_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Renouvelle le token d'accès à partir d'un token de rafraîchissement.
         */
        post: operations["apps_accounts_api_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Déconnexion : avec des JWT sans état, le client supprime ses tokens.
         *
         *     L'endpoint sert de point d'extension (journalisation / future
         *     liste de révocation) et confirme la déconnexion.
         */
        post: operations["apps_accounts_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Retourne les informations de l'organisateur connecté.
         */
        get: operations["apps_accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change le mot de passe de l'organisateur connecté.
         */
        post: operations["apps_accounts_api_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Liste tous les comptes (admin uniquement).
         */
        get: operations["apps_accounts_api_list_users"];
        put?: never;
        /**
         * Create User
         * @description Crée un compte organisateur ou admin (admin uniquement).
         */
        post: operations["apps_accounts_api_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Supprime un compte (admin uniquement).
         *
         *     Refusé pour son propre compte, ou si l'utilisateur a créé des activités
         *     (le désactiver à la place pour ne pas perdre les données liées).
         */
        delete: operations["apps_accounts_api_delete_user"];
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Modifie un compte (nom, email, rôle, activation) — admin uniquement.
         */
        patch: operations["apps_accounts_api_update_user"];
        trace?: never;
    };
    "/api/auth/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset User Password
         * @description Réinitialise le mot de passe d'un utilisateur (admin uniquement).
         */
        post: operations["apps_accounts_api_reset_user_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Journal d'audit des actions (admin uniquement), 500 entrées les plus récentes.
         */
        get: operations["apps_accounts_api_list_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{user_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User Audit
         * @description Journal d'audit d'un utilisateur précis (admin uniquement).
         */
        get: operations["apps_accounts_api_user_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activites
         * @description Liste les activités : toutes pour un admin, seulement les siennes
         *     pour un organisateur (AUTH-04).
         */
        get: operations["apps_activites_api_list_activites"];
        put?: never;
        /**
         * Create Activite
         * @description Crée une activité (token QR généré automatiquement).
         */
        post: operations["apps_activites_api_create_activite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/stats-globales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats Globales
         * @description Statistiques transverses du tableau de bord (DASH-01).
         *
         *     `nb_participants_uniques` compte les personnes distinctes par numéro de CNI,
         *     sans double comptage entre activités.
         */
        get: operations["apps_activites_api_stats_globales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/personnes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Personnes
         * @description Annuaire des personnes distinctes (regroupées par numéro de CNI).
         *
         *     L'identité affichée provient de l'inscription la plus récente de chaque
         *     personne ; `nb_activites` compte ses activités distinctes.
         */
        get: operations["apps_activites_api_list_personnes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/personnes/historique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historique Personne
         * @description Historique de participation d'une personne (toutes ses inscriptions).
         *
         *     Un organisateur ne voit que les participations à ses propres activités.
         */
        get: operations["apps_activites_api_historique_personne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activite
         * @description Détail d'une activité (visible par tous).
         */
        get: operations["apps_activites_api_get_activite"];
        /**
         * Update Activite
         * @description Modifie une activité (créateur ou admin ; token QR inchangé — ACT-04).
         */
        put: operations["apps_activites_api_update_activite"];
        post?: never;
        /**
         * Delete Activite
         * @description Supprime une activité (créateur ou admin — ACT-06).
         *
         *     Refusé si l'activité contient des participants (elle ne peut qu'être
         *     archivée dans ce cas).
         */
        delete: operations["apps_activites_api_delete_activite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone Activite
         * @description Clone une activité visible. La copie appartient à l'utilisateur courant.
         */
        post: operations["apps_activites_api_clone_activite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}/qrcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qrcode
         * @description Génère le QR Code PNG encodant l'URL du formulaire public (ACT-02).
         */
        get: operations["apps_activites_api_get_qrcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}/statut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Statut
         * @description Ouvre / ferme / archive la collecte (créateur ou admin — ACT-05).
         */
        patch: operations["apps_activites_api_set_statut"];
        trace?: never;
    };
    "/api/activites/{activite_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Participants
         * @description Liste paginée et filtrée des participants d'une activité (DASH-03).
         */
        get: operations["apps_activites_api_list_participants"];
        put?: never;
        /**
         * Add Participant
         * @description Ajout manuel d'un participant (créateur ou admin — sans photos CNI).
         */
        post: operations["apps_activites_api_add_participant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Participants Stats
         * @description Statistiques d'une activité (DASH-05).
         */
        get: operations["apps_activites_api_participants_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Participant
         * @description Fiche détaillée d'un participant (DASH-04).
         */
        get: operations["apps_activites_api_get_participant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activites/{activite_id}/participants/{participant_id}/photo/{cote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Participant Photo
         * @description Sert une photo CNI (accès protégé par JWT — IMG-03).
         */
        get: operations["apps_activites_api_participant_photo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/activite/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activite Publique
         * @description Vérifie le token et retourne les infos publiques de l'activité (FORM-01).
         */
        get: operations["apps_participants_api_get_activite_publique"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/activite/{token}/participer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Participer
         * @description Enregistre un participant avec ses photos CNI (FORM-02 à FORM-06).
         */
        post: operations["apps_participants_api_participer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/activites/{activite_id}/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Excel
         * @description EXP-01 — Liste des participants au format .xlsx.
         */
        get: operations["apps_exports_api_export_excel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/activites/{activite_id}/pdf-liste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Presence Pdf
         * @description EXP-03 — Liste de présence à signer (PDF A4).
         */
        get: operations["apps_exports_api_export_presence_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/activites/{activite_id}/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Cni Zip
         * @description EXP-04 — Archive ZIP des fiches PDF CNI.
         */
        get: operations["apps_exports_api_export_cni_zip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/activites/{activite_id}/qrcode-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Qrcode Pdf
         * @description Affiche PDF du QR Code (infos activité + QR Code).
         */
        get: operations["apps_exports_api_export_qrcode_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/participants/{participant_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Participant Pdf
         * @description EXP-02 — Fiche CNI individuelle (PDF).
         */
        get: operations["apps_exports_api_export_participant_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/activites/{activite_id}/historique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export History
         * @description EXP-06 — Journal des exports générés pour une activité.
         */
        get: operations["apps_exports_api_export_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** TokenOut */
        TokenOut: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** AccessOut */
        AccessOut: {
            /** Access */
            access: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Detail */
            detail: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** ChangePasswordIn */
        ChangePasswordIn: {
            /** Ancien Mot De Passe */
            ancien_mot_de_passe: string;
            /** Nouveau Mot De Passe */
            nouveau_mot_de_passe: string;
        };
        /** UserListOut */
        UserListOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Nb Activites
             * @default 0
             */
            nb_activites: number;
        };
        /** UserCreateIn */
        UserCreateIn: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default organisateur
             */
            role: string;
        };
        /** UserUpdateIn */
        UserUpdateIn: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Role */
            role?: string | null;
        };
        /** AdminResetPwdIn */
        AdminResetPwdIn: {
            /** Nouveau Mot De Passe */
            nouveau_mot_de_passe: string;
        };
        /** AuditLogOut */
        AuditLogOut: {
            /** Username */
            username: string;
            /** Action */
            action: string;
            /** Action Label */
            action_label: string;
            /** Objet */
            objet: string;
            /** Ip Address */
            ip_address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ActiviteOut */
        ActiviteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nom */
            nom: string;
            /** Description */
            description: string;
            /**
             * Date Debut
             * Format: date-time
             */
            date_debut: string;
            /**
             * Date Fin
             * Format: date-time
             */
            date_fin: string;
            /** Ville */
            ville: string;
            /** Lieu */
            lieu: string;
            /**
             * Token Qr
             * Format: uuid
             */
            token_qr: string;
            /** Statut */
            statut: string;
            /** Form Url */
            form_url: string;
            created_by: components["schemas"]["CreatedByOut"];
            /** Can Edit */
            can_edit: boolean;
            /** Nb Participants */
            nb_participants: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CreatedByOut */
        CreatedByOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
        };
        /** ActiviteIn */
        ActiviteIn: {
            /** Nom */
            nom: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Date Debut
             * Format: date-time
             */
            date_debut: string;
            /**
             * Date Fin
             * Format: date-time
             */
            date_fin: string;
            /** Ville */
            ville: string;
            /** Lieu */
            lieu: string;
        };
        /** GlobalStatsOut */
        GlobalStatsOut: {
            /** Nb Activites */
            nb_activites: number;
            /** Nb Participants Uniques */
            nb_participants_uniques: number;
        };
        /** PersonneOut */
        PersonneOut: {
            /** Numero Cni */
            numero_cni: string;
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Structure */
            structure: string;
            /** Fonction */
            fonction: string;
            /** Telephone Wave */
            telephone_wave: string;
            /** Email */
            email: string;
            /** Nb Activites */
            nb_activites: number;
            /**
             * Derniere Participation
             * Format: date-time
             */
            derniere_participation: string;
            /** Cni Complete */
            cni_complete: boolean;
        };
        /** HistoriqueLigneOut */
        HistoriqueLigneOut: {
            /**
             * Participant Id
             * Format: uuid
             */
            participant_id: string;
            /**
             * Activite Id
             * Format: uuid
             */
            activite_id: string;
            /** Activite Nom */
            activite_nom: string;
            /** Activite Lieu */
            activite_lieu: string;
            /**
             * Horodatage
             * Format: date-time
             */
            horodatage: string;
            /** Cni Complete */
            cni_complete: boolean;
        };
        /** HistoriqueOut */
        HistoriqueOut: {
            /** Numero Cni */
            numero_cni: string;
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Structure */
            structure: string;
            /** Fonction */
            fonction: string;
            /** Telephone Wave */
            telephone_wave: string;
            /** Email */
            email: string;
            /** Nb Activites */
            nb_activites: number;
            /** Participations */
            participations: components["schemas"]["HistoriqueLigneOut"][];
        };
        /** ActiviteUpdate */
        ActiviteUpdate: {
            /** Nom */
            nom?: string | null;
            /** Description */
            description?: string | null;
            /** Date Debut */
            date_debut?: string | null;
            /** Date Fin */
            date_fin?: string | null;
            /** Ville */
            ville?: string | null;
            /** Lieu */
            lieu?: string | null;
            /** Statut */
            statut?: string | null;
        };
        /** StatutIn */
        StatutIn: {
            /** Statut */
            statut: string;
        };
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PagedParticipantListOut */
        PagedParticipantListOut: {
            /** Items */
            items: components["schemas"]["ParticipantListOut"][];
            /** Count */
            count: number;
        };
        /** ParticipantListOut */
        ParticipantListOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Structure */
            structure: string;
            /** Fonction */
            fonction: string;
            /** Telephone Wave */
            telephone_wave: string;
            /** Email */
            email: string;
            /** Numero Cni */
            numero_cni: string;
            /**
             * Horodatage
             * Format: date-time
             */
            horodatage: string;
            /** Photo Recto Url */
            photo_recto_url: string;
            /** Photo Verso Url */
            photo_verso_url: string;
            /** Cni Complete */
            cni_complete: boolean;
        };
        /**
         * ParticipantManualIn
         * @description Ajout manuel d'un participant par un organisateur (sans photos CNI).
         */
        ParticipantManualIn: {
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Structure */
            structure: string;
            /** Fonction */
            fonction: string;
            /** Telephone Wave */
            telephone_wave: string;
            /** Email */
            email: string;
            /** Numero Cni */
            numero_cni: string;
        };
        /** StatsOut */
        StatsOut: {
            /** Total */
            total: number;
            /** Cni Completes */
            cni_completes: number;
            /** Cni Incompletes */
            cni_incompletes: number;
            /** Par Structure */
            par_structure: components["schemas"]["StructureStat"][];
        };
        /** StructureStat */
        StructureStat: {
            /** Structure */
            structure: string;
            /** Count */
            count: number;
        };
        /** ActivitePublicOut */
        ActivitePublicOut: {
            /** Nom */
            nom: string;
            /** Ville */
            ville: string;
            /** Lieu */
            lieu: string;
            /**
             * Date Debut
             * Format: date-time
             */
            date_debut: string;
            /**
             * Date Fin
             * Format: date-time
             */
            date_fin: string;
            /** Statut */
            statut: string;
            /** Is Open */
            is_open: boolean;
        };
        /** ParticipantOut */
        ParticipantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Structure */
            structure: string;
            /** Fonction */
            fonction: string;
            /** Telephone Wave */
            telephone_wave: string;
            /** Email */
            email: string;
            /** Numero Cni */
            numero_cni: string;
            /**
             * Horodatage
             * Format: date-time
             */
            horodatage: string;
        };
        /** ParticiperSchema */
        ParticiperSchema: {
            /** Nom */
            nom: string;
            /** Prenom */
            prenom: string;
            /** Structure */
            structure: string;
            /** Fonction */
            fonction: string;
            /** Telephone Wave */
            telephone_wave: string;
            /** Email */
            email: string;
            /** Numero Cni */
            numero_cni: string;
        };
        /** ExportLogOut */
        ExportLogOut: {
            /** Type */
            type: string;
            /** Type Label */
            type_label: string;
            /** Nb Entrees */
            nb_entrees: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Utilisateur */
            utilisateur: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
        };
    };
    apps_accounts_api_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessOut"];
                };
            };
        };
    };
    apps_accounts_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    apps_accounts_api_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_accounts_api_list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"][];
                };
            };
        };
    };
    apps_accounts_api_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
        };
    };
    apps_accounts_api_delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_accounts_api_update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
        };
    };
    apps_accounts_api_reset_user_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminResetPwdIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_accounts_api_list_audit: {
        parameters: {
            query?: {
                action?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogOut"][];
                };
            };
        };
    };
    apps_accounts_api_user_audit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogOut"][];
                };
            };
        };
    };
    apps_activites_api_list_activites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiviteOut"][];
                };
            };
        };
    };
    apps_activites_api_create_activite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiviteIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiviteOut"];
                };
            };
        };
    };
    apps_activites_api_stats_globales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStatsOut"];
                };
            };
        };
    };
    apps_activites_api_list_personnes: {
        parameters: {
            query?: {
                search?: string | null;
                structure?: string | null;
                cni?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonneOut"][];
                };
            };
        };
    };
    apps_activites_api_historique_personne: {
        parameters: {
            query: {
                numero_cni: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoriqueOut"];
                };
            };
        };
    };
    apps_activites_api_get_activite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiviteOut"];
                };
            };
        };
    };
    apps_activites_api_update_activite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiviteUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiviteOut"];
                };
            };
        };
    };
    apps_activites_api_delete_activite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_activites_api_clone_activite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiviteOut"];
                };
            };
        };
    };
    apps_activites_api_get_qrcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_activites_api_set_statut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatutIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiviteOut"];
                };
            };
        };
    };
    apps_activites_api_list_participants: {
        parameters: {
            query?: {
                search?: string | null;
                structure?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedParticipantListOut"];
                };
            };
        };
    };
    apps_activites_api_add_participant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantManualIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantListOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_activites_api_participants_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    apps_activites_api_get_participant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantListOut"];
                };
            };
        };
    };
    apps_activites_api_participant_photo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
                participant_id: string;
                cote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_participants_api_get_activite_publique: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitePublicOut"];
                };
            };
        };
    };
    apps_participants_api_participer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Nom */
                    nom: string;
                    /** Prenom */
                    prenom: string;
                    /** Structure */
                    structure: string;
                    /** Fonction */
                    fonction: string;
                    /** Telephone Wave */
                    telephone_wave: string;
                    /** Email */
                    email: string;
                    /** Numero Cni */
                    numero_cni: string;
                    /**
                     * Photo Cni Recto
                     * Format: binary
                     */
                    photo_cni_recto: string;
                    /**
                     * Photo Cni Verso
                     * Format: binary
                     */
                    photo_cni_verso: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
        };
    };
    apps_exports_api_export_excel: {
        parameters: {
            query?: {
                search?: string | null;
                structure?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                cni?: string | null;
            };
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_exports_api_export_presence_pdf: {
        parameters: {
            query?: {
                search?: string | null;
                structure?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                cni?: string | null;
            };
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_exports_api_export_cni_zip: {
        parameters: {
            query?: {
                search?: string | null;
                structure?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                cni?: string | null;
            };
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_exports_api_export_qrcode_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_exports_api_export_participant_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_exports_api_export_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportLogOut"][];
                };
            };
        };
    };
}
