# Generated by Django 6.0.5 on 2026-06-03 13:48

import apps.participants.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('structure', models.CharField(max_length=255, verbose_name='structure')),
                ('fonction', models.CharField(max_length=255, verbose_name='fonction')),
                ('telephone_wave', models.CharField(max_length=20, verbose_name='téléphone Wave')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('numero_cni', models.CharField(max_length=50, verbose_name='numéro CNI')),
                ('photo_cni_recto', models.ImageField(upload_to=apps.participants.models.cni_upload_path, verbose_name='photo CNI recto')),
                ('photo_cni_verso', models.ImageField(upload_to=apps.participants.models.cni_upload_path, verbose_name='photo CNI verso')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activites.activite', verbose_name='activité')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
                'ordering': ['-horodatage'],
                'constraints': [models.UniqueConstraint(fields=('activite', 'numero_cni'), name='unique_cni_par_activite')],
            },
        ),
    ]
