# Generated by Django 6.0.5 on 2026-06-03 14:34

import apps.participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photo_cni_recto',
            field=models.ImageField(blank=True, upload_to=apps.participants.models.cni_upload_path, verbose_name='photo CNI recto'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='photo_cni_verso',
            field=models.ImageField(blank=True, upload_to=apps.participants.models.cni_upload_path, verbose_name='photo CNI verso'),
        ),
    ]
