# Generated by Django 6.0.5 on 2026-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('organisateur', 'Organisateur')], default='organisateur', max_length=20, verbose_name='rôle'),
        ),
    ]
