# Generated by Django 6.0.5 on 2026-06-05 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, verbose_name="nom d'utilisateur")),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Échec de connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('activite_create', "Création d'activité"), ('activite_update', "Modification d'activité"), ('activite_statut', 'Changement de statut'), ('activite_delete', "Suppression d'activité"), ('activite_clone', "Clonage d'activité"), ('export', 'Export'), ('user_create', 'Création de compte'), ('user_update', 'Modification de compte'), ('user_delete', 'Suppression de compte'), ('user_reset_pwd', 'Réinitialisation de mot de passe')], max_length=30, verbose_name='action')),
                ('objet', models.CharField(blank=True, max_length=255, verbose_name='objet')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
