# Generated by Django 6.0.5 on 2026-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Échec de connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('activite_create', "Création d'activité"), ('activite_update', "Modification d'activité"), ('activite_statut', 'Changement de statut'), ('activite_delete', "Suppression d'activité"), ('activite_clone', "Clonage d'activité"), ('participant_create', "Ajout manuel d'un participant"), ('participant_update', "Modification d'un participant"), ('export', 'Export'), ('user_create', 'Création de compte'), ('user_update', 'Modification de compte'), ('user_delete', 'Suppression de compte'), ('user_reset_pwd', 'Réinitialisation de mot de passe')], max_length=30, verbose_name='action'),
        ),
    ]
