# Generated by Django 6.0.5 on 2026-07-10 00:44

import apps.justificatifs.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0003_activite_budget_alloue_activite_type_mission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipe', models.CharField(blank=True, default='', max_length=255, verbose_name='équipe')),
                ('categorie', models.CharField(choices=[('carburant', 'Carburant'), ('peage', 'Péage'), ('communication', 'Communication'), ('perdiem', 'Perdiem'), ('presence', 'Liste de présence'), ('collation', 'Collation')], max_length=20, verbose_name='catégorie')),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, help_text='Saisi pour perdiem / collation. Pour carburant, péage et communication, il est calculé comme la somme des reçus.', max_digits=12, null=True, verbose_name='montant total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='activites.activite', verbose_name='mission')),
                ('activite_collation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_collation', to='activites.activite', verbose_name='activité liée (collation)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'justificatif',
                'verbose_name_plural': 'justificatifs',
                'ordering': ['categorie', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to=apps.justificatifs.models.piece_upload_path, verbose_name='fichier')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant du reçu (carburant, péage, communication).', max_digits=12, null=True, verbose_name='montant')),
                ('libelle', models.CharField(blank=True, default='', max_length=255, verbose_name='libellé')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='type MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('justificatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='justificatifs.justificatif', verbose_name='justificatif')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['created_at'],
            },
        ),
    ]
