# Generated by Django 6.0.5 on 2026-07-10 00:46

import apps.justificatifs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificatifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(max_length=255, upload_to=apps.justificatifs.models.piece_upload_path, verbose_name='fichier'),
        ),
    ]
