# Generated by Django 6.0.5 on 2026-06-03 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('lieu', models.CharField(max_length=255, verbose_name='lieu')),
                ('token_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token QR Code')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouverte'), ('ferme', 'Fermée'), ('archive', 'Archivée')], default='ouvert', max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL, verbose_name='organisateur')),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
