# Generated by Django 6.0.5 on 2026-06-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='ville',
            field=models.CharField(default='', max_length=255, verbose_name='ville'),
        ),
    ]
