# Generated by Django 6.0.5 on 2026-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_activite_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='budget_alloue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total remis pour une mission terrain, base du taux de conciliation (montants justifiés ÷ budget alloué).', max_digits=12, null=True, verbose_name='budget alloué'),
        ),
        migrations.AddField(
            model_name='activite',
            name='type_mission',
            field=models.CharField(choices=[('atelier', 'Atelier (en salle)'), ('terrain', 'Mission terrain')], default='atelier', max_length=10, verbose_name='type de mission'),
        ),
    ]
